### ISSUE TITLE
Administrative things

### ISSUE THREAD

**Issue by missymessa** [primordially/primordially#2]
- [x] Admin roles (need to create a GitHub org for this)
- [x] PR gates into master? 
- [x] Set up AzDO for build/test/(eventual packaging)
- [x] Communication channels outside of Teams? (probs Discord)
- [x] Create a better looking badge for the Discord link: for reference https://github.com/cdr/code-server/pull/364
- [x] Come up with a better name for our project

**Comment by adiaaida** [comment]
Maybe discord for communications? I only have teams on the work laptop, which I do not use outside of work.

**Comment by missymessa** [comment]
Yeah, I'm not wanting to use Teams for outside of work stuff either, especially if we end up having non-work folks collaborate with us.

**Comment by jonfortescue** [comment]
Discord is also good if other collaborators want to join eventually; we can just throw a link in the README.

**Comment by missymessa** [comment]
Okay, so far I got a pipeline to AzDO configured, protected the master branch. Working on setting folks up as admins so we can get around the branch protections I just put in place :)

**Comment by missymessa** [comment]
Looks like I'm going to have to set up a GitHub Org (I can do a free one). Are we married to the PCSharpGen name? Do we want to call it something else? Once we figure that out, I'll set up our stuff using that name and then give admins privs n' stuff.

**Comment by missymessa** [comment]
Project name is `primordial.ly`. Created an org for the project, too.

**Comment by missymessa** [comment]
Made an org, assigned folks to owner roles. We're good to go :)
